### ISSUE TITLE
error: couldn't IRGen expression after adding CubiCapture

### ISSUE THREAD

**Issue by joeltrew** [CubiCasa/ios-sdk-distribution#1]
Hi there,

After installing the SDK through Cocoapods and trying to use the debugger to print values using commands like `po` and `p` it always fails and prints the following:

```
error: virtual filesystem overlay file '/Users/marnix/Library/Developer/Xcode/DerivedData/CubiCapture-eojkhhwgyyfwbpaqccbabcrlebud/Build/Intermediates.noindex/ArchiveIntermediates/CubiCapture/IntermediateBuildFilesPath/CubiCapture.build/Release-iphonesimulator/CubiCapture.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

I noticed its printing an absolute path to another user `(/Users/marnix/Library/...)`  which might be an issue?
I did a bit of digging and I found [this post](https://thi.im/posts/couldnt-irgen-expression-no-source-code/) which also makes some suggestions but couldn't get it working from my side, I wonder if there's additional export option required.

Any help is much appreciated! Thanks

**Comment by Ketkukelmi** [comment]
Hello, we are looking in to the issue 👍

**Comment by MarnixArnold** [comment]
It turns out this issue disappears when you update Xcode to version 12.5.
